### ISSUE TITLE
Duplication of taxa within Territory-taxa explorer

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ukotas#1]
When viewing taxa for a territory, some names are duplicated
![issue - ukotas](https://user-images.githubusercontent.com/2699478/179238539-3b4c6a84-b2cc-4d2c-9ae3-4deffb04553f.JPG)

**Comment by StephRorke** [comment]
To add to this particular example:

![image](https://user-images.githubusercontent.com/35227065/180198595-c4a23498-8deb-42a5-a327-c26844f18bd7.png)

**Comment by StephRorke** [comment]
Another similar example of this type of duplication is with Agapanthus praecox, again this has an entry for both Saint Helena and Tristan da Cuhna but in this example it's the Saint Helena page that links to both entries with none on Tristan da Cuhna's page

**Comment by johnvanbreda** [comment]
2 issues found. First, a bug in the code which sets the territory on the hierarchy of taxonomic terms when you save a species account. So although the 2 accounts correctly had TdC and SH as their territories, when the SH account was attached to the existing taxonomic lineage, it did not update the lineage to reflect that it should be for both SH and TdC. I've fixed that issue.

The second issue is that the hiearchy species level is filtered based on the attached term' territories, not on the species account's  single territory. So both versions of the account appear in both places. Need to change the way this contextual filter is applied.

**Comment by johnvanbreda** [comment]
I've also fixed the second issue by changing to a contextual filter on the content (species node) rather than the taxonomy term.

I've re-saved the TdC Agapanthus praecox species account which has replaced it in the correct location in the hierarchy.

I have, however, noticed one further issue in that the count of species for the genus is wrong, showing 2 when there is 1 species. It must be including species from both territories.

**Comment by johnvanbreda** [comment]
I've fixed the count issue by altering the AJAX controller code to supply the territory argument twice - once for the terms and once for the account nodes. So I think this issue is now done.
