### ISSUE TITLE
Add functionality to allocate taxonomic information for species names without GBIF records

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/ukotas#13]
- Currently species entries without a GBIF link are not included in the taxonomic hierarchy menus and therefore can only be accessed by searching for the species names directly. Provide an option to allow for inclusion of these species within the menu lists.
- In these cases it would also help to replace the map with a statement to indicate there is not a GBIF entry or a at least a label on the page

**Comment by StephRorke** [comment]
Add field to data structure to hold boolean for 'matched to species' 
this field will be added to the import template and set to true where we have matched the catalog of life entry with a match to the species name, it will be set to false where we have only matched to a higher taxonomic category. 
The default for this field for records already entered where the catalog of life field has been completed will be true.

It would be useful to be able to view this field from the review page.

**Comment by johnvanbreda** [comment]
I've added the Matched to species field and set it for the existing data if the CoL ID is present. 

For info, here's the code temporarily run on cron to populate the existing data in case it's needed again:
```php
function ukotas_extras_cron() {
  $nids = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'species_account')
    ->exists('field_catalogue_of_life_id')
    ->notexists('field_matched_to_species')
    ->range(0, 200)
    ->execute();
  $nodes = Node::loadMultiple($nids);
  foreach ($nodes as $node) {
    $node->set('field_matched_to_species', TRUE);
    $node->save();
  }
  $nids = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'species_account')
    ->exists('field_catalogue_of_life_id')
    ->notexists('field_matched_to_species')
    ->execute();
  \Drupal::messenger()->addMessage('Remaining to do ' . count($nids));
}
```
