### ISSUE TITLE
Identifying species where no CoL is available

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/ukotas#18]
It would be good to be able to tag species for which there is no match on CoL available. 
This would allow those reviewing species to save time re-visiting the entry to attempt to obtain a link. This may only be an issue with the existing St Helena and TdC species entries as going forward we will provide the link along with the data import and therefore if new entries are without a CoL link we can assume it was not available at the time, whereas at present we don't know if it is not available or just incomplete.

**Comment by johnvanbreda** [comment]
I've added a tickbox for this - should it appear on any of the list views or be available as a filter?

**Comment by StephRorke** [comment]
@johnvanbreda thank you! If it could be visible on the review species page that would be great.

**Comment by johnvanbreda** [comment]
Done
