### ISSUE TITLE
Duplication of taxa - added in error

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/ukotas#2]
Duplicate entries for a species name and authority from different resources added for one territory e.g. Cornu aspersum https://dev-ceh-ukotas.pantheonsite.io/species/cornu-aspersum-0 and https://dev-ceh-ukotas.pantheonsite.io/species/cornu-aspersum

Can a system check be added to minimise the chance of entering duplicate species names for the same territory?

What is the cleanest way to remove duplicates?

**Comment by StephRorke** [comment]
John, please can you provide the means to easily identify where multiple entries for the same species within a territory have been added, from the website review page or other logical location.

**Comment by StephRorke** [comment]
Can the delete button be made available from the review page or the territory added to the Content page so we can quickly access the correct record to delete.

**Comment by johnvanbreda** [comment]
A duplicates view has been added, as well as a delete link on the review page.

**Comment by StephRorke** [comment]
@johnvanbreda would it be possible to make some changes to the review species duplicates page please to cut down on the number of page visits needed to clean up the duplicate entries?
Instead of listing only the distinct species names per territory along with a count on the duplicates page, can you include all duplicated species entries in the list ordered by species name and territory along with a link to directly edit the record and a link to delete the record. 
This would save us having to look at the duplicates list then switching to the review page, search for the species name and then edit or delete.
Alternatively when clicking on the name in the current duplicates list, perhaps this could open the review species page with the search already performed so only the relevant entries are shown. At the moment the species name links to one of the duplicated entries in view mode. Perhaps this is the cleaner way of doing it? Open to suggestions though. Thanks

**Comment by johnvanbreda** [comment]
I've added a link to the review page, which is filtered by species name and territory, so effectively your 2nd option.
