### ISSUE TITLE
Duplicate of unknown origin

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/ukotas#3]
A single entry for Acherontia atropos was included within the import file for Saint Helena only, however there are two entries present in the website with identical catalogue of life IDs and GBIF Taxon IDs. 
https://dev-ceh-ukotas.pantheonsite.io/species/acherontia-atropos-0
https://dev-ceh-ukotas.pantheonsite.io/species/acherontia-atropos

**Comment by StephRorke** [comment]
Possibly a user error as I haven't identified other examples of this type of duplication. I will leave this here just in case the error can be traced to a system error. We will delete the duplicate once  eliminated the possibility of a system error

**Comment by johnvanbreda** [comment]
In isolation, it seems very unlikely to be a system error, especially as the duplicate was created by me at the time I was doing lots of uploading. So I think it is safe to delete the duplcate and close this.

**Comment by johnvanbreda** [comment]
Re-opening, as I've realised the import node csv custom module is supposed to detect a duplicate on the basis of the title and territory being the same, so this doesn't appear to work.

**Comment by johnvanbreda** [comment]
Closing again, as testing today shows it does work, so maybe a temporary bug.
