### ISSUE TITLE
Add filters to review page

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/ukotas#7]
As well as being able to search for species using names on the review page it would be really helpful to be able to filter by territory, blank GBIF/ Catalogue of life fields etc.

**Comment by StephRorke** [comment]
I can see you have added the columns I requested, thank you.

**Comment by johnvanbreda** [comment]
Filters also added.

**Comment by StephRorke** [comment]
@johnvanbreda after having applied filters to the review page and then selected a species to edit, on saving the changes made, the user is returned to the unfiltered list on the review page, is it possible to retain the applied filters so they don't need to be reapplied to reach the subset of data that is being worked on? Thanks

**Comment by StephRorke** [comment]
@johnvanbreda apologies, it actually seems to be functioning this way now, so perhaps I was inadvertently refreshing the page before?
