### ISSUE TITLE
View and download species list for each territory

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/ukotas#9]
This would be helpful to have as an available output for users and also for those assessing new resources to check whether or not a species is already in the database and how much information had been added / whether it agrees with previously included data. 

If it were possible to include an option to export all associated information for each species this would help with any gap filling activity that was undertaken.

**Comment by StephRorke** [comment]
This feature only needs to be available to logged in users.

**Comment by johnvanbreda** [comment]
Done - see https://dev-ceh-ukotas.pantheonsite.io/all-species-data. There is a CSV button in the bottom left corner for downloads.
